pipeline {
    agent any
    stages {
        stage('Run tests using docker') {
            parallel {
                stage ('UI tests on the chrome in the linux container') {
                    steps {
                        script {

                        //run linux with chrome server. change this comment
                        // alternative run: docker-compose -f pipeline/containers/pseudo_compose/docker-compose.yml up --abort-on-container-exit --exit-code-from py_runner
                        sh 'docker-compose -f pipeline/containers/pseudo_compose/docker-compose.yml run --rm py_runner'
                        }
                        }
                    }
                stage('API tests in the python container') {
                    steps {
                        script {

                        sh 'docker build -f ./pipeline/containers/python_api/Dockerfile -t pytest_runner .'
                        sh 'docker run --rm --mount type=bind,src=' + (pwd) + ',target=/tests_project pytest_runner'
                        }

                        }
                    }
                }

            }
        }

    post {
        always {

            script {
                        allure([
                                //allure commandline: 'allure',
                                includeProperties: false,
                                jdk: '',
                                results: [[path: 'test_results']]
                        ])
                    }
            //bat 'docker-compose -f pipeline/containers/pseudo_compose/docker-compose.yml down'
            }
        }
}