pipeline {
    agent any

    stages {
        stage('Run API tests using docker') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'inside_of_docker_container']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/jujga/TestTaskEvo']]])
                bat 'docker build -t pytest_runner .'
                bat 'docker run --rm --mount type=bind,src=' + pwd() + ',target=/tests_project/ pytest_runner'
                //bat(readFile("D:/cmds/do_image_python.cmd"))

                }
            }
        stage('Run UI tests using docker') {
            steps {
                //checkout([$class: 'GitSCM', branches: [[name: 'inside_of_docker_container']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/jujga/TestTaskEvo']]])
                bat 'docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome:3.141.59-20210607'
                bat 'pytest -m ui --alluredir ./test_results --start_from_jenkins=True'

                }
            }
        }


    post {
        always {
            script {
                        allure([
                                //allure commandline: 'allure',
                                includeProperties: false,
                                jdk: '',
                                results: [[path: 'test_results']]
                        ])
                    }
                }
        }
}
    // stage('Run REST tests') {
        //     steps {
        //         bat(readFile("C:/Users/jujga/PycharmProjects/TestTaskEvo/run_rest_test.bat"))
        //     }
        // }

        // stage('reports') {
        //     steps {
        //         script {
        //                 allure([
        //                         //allure commandline: 'allure',
        //                         includeProperties: false,
        //                         jdk: '',
        //                         results: [[path: 'test_results']]
        //                 ])
        //             }
        //         }
        //     }

